### ISSUE TITLE
Broken on Windows: Need to use shutil.get_terminal_size()

### ISSUE THREAD

**Issue by DevOptimusPrime** [jart/fabulous#13]
Trying to the the simple examples working but the 
`from fabulous.color import bold`

statement fails with 
`>>> from fabulous.color import bold
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python35\lib\site-packages\fabulous\color.py", line 31, in <module>
    from fabulous import utils, xterm256, grapefruit
  File "D:\Python35\lib\site-packages\fabulous\utils.py", line 25, in <module>
    import fcntl
ImportError: No module named 'fcntl'
`

**Comment by jart** [comment]
How could that be? This is a standard module in both Python 2 and 3.
- https://docs.python.org/2/library/fcntl.html
- https://docs.python.org/3.3/library/fcntl.html

**Comment by DevOptimusPrime** [comment]
My guess, but I am no expert, is that since it's Unix specific it only gets installed on Unix environments? 

My Python 3.5 installation on Windows 7 does not contain a fcntl library, only some tests in the lib\test directory called test_fcntl_cpython.....

**Comment by jart** [comment]
Ohhh. Then this is something we definitely need to fix. It seems the way to do this, is to update the dimensions method in util.py to use this library: https://pypi.python.org/pypi/backports.shutil_get_terminal_size as I learned from http://stackoverflow.com/a/14422538

Would you like to contribute this as a pull request, since you actually use windows?

**Comment by DevOptimusPrime** [comment]
I'm a pretty green python dev - I'd be in over my head most likely (please forgive lol). I'd gladly test it though.

**Comment by jart** [comment]
If I get bored one of these weekends, I'll consider writing it. But I'm hesitant to do so, because I have no Windows computer to test further. For all I know, other functionality might be broken too. Hopefully another volunteer will come along to implement the Windows support.

**Comment by willtheorangeguy** [comment]
I can test it, since I have a Windows computer (Windows 10 to be precise). 
But I don't think I will be able to write it. I might be able to make some slight changes though.
I'll try when I have time.

**Comment by minchinweb** [comment]
@jart: check out my implementation!

It replies on `shutil.get_terminal_size`, which was added to the standard library for Python 3.3. Failing that it fallsover to a backported version of the same (added to the setup.py requirements section conditionally).

It also changes the default terminal size to (80,24), which seems to be a much more common default.

Tested and works on Windows!

**Comment by willtheorangeguy** [comment]
Thanks for working on this!
I'll take a look at it!
